// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBanVeXeBenXeMienDong.Models;

#nullable disable

namespace QuanLyBanVeXeBenXeMienDong.Migrations
{
    [DbContext(typeof(BenXeMienDongContext))]
    [Migration("20250323121435_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.CSKH", b =>
                {
                    b.Property<string>("MaCSKH")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNhaXe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayCSKH")
                        .HasColumnType("datetime2");

                    b.HasKey("MaCSKH");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNhaXe");

                    b.ToTable("CSKH", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.ChuyenXe", b =>
                {
                    b.Property<string>("MaChuyen")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiemDen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiemDi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("GioKhoiHanh")
                        .HasColumnType("time");

                    b.Property<string>("MaXe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayKhoiHanh")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChuyen");

                    b.HasIndex("MaXe");

                    b.ToTable("CHUYEN_XE", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HovaTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("MaKh");

                    b.ToTable("KHACH_HANG", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.LoaiXe", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoai");

                    b.ToTable("LOAI_XE", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.NhaXe", b =>
                {
                    b.Property<string>("MaNhaXe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenNhaXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaNhaXe");

                    b.ToTable("NHA_XE", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.NhanVien", b =>
                {
                    b.Property<string>("MANV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HovaTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNhaXe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("MANV");

                    b.HasIndex("MaNhaXe");

                    b.ToTable("NHAN_VIEN", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.SoGheSoGiuong", b =>
                {
                    b.Property<string>("MaSoGhe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(0);

                    b.Property<string>("MaXe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(1);

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSoGhe", "MaXe");

                    b.HasIndex("MaXe");

                    b.ToTable("SoGhe_SoGiuong", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.TaiXe", b =>
                {
                    b.Property<string>("MaTaiXe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BangLai")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("HovaTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("KinhNghiem")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("MaTaiXe");

                    b.ToTable("TAI_XE", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.ThanhToan", b =>
                {
                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNhaXe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaVeXe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhuongThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaGiaoDich");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNhaXe");

                    b.HasIndex("MaVeXe");

                    b.ToTable("THANH_TOAN", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.VeXe", b =>
                {
                    b.Property<string>("MaVeXe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MANV")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaChuyen")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNhaXe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSoGhe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaXe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayDatVe")
                        .HasColumnType("datetime2");

                    b.HasKey("MaVeXe");

                    b.HasIndex("MANV");

                    b.HasIndex("MaChuyen");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNhaXe");

                    b.HasIndex("MaSoGhe", "MaXe");

                    b.ToTable("VE_XE", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.Xe", b =>
                {
                    b.Property<string>("MaXe")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNhaXe")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("SoLuongGhe")
                        .HasColumnType("int");

                    b.HasKey("MaXe");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaNhaXe");

                    b.ToTable("XE", (string)null);
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.CSKH", b =>
                {
                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.NhaXe", "NhaXe")
                        .WithMany()
                        .HasForeignKey("MaNhaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhaXe");
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.ChuyenXe", b =>
                {
                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.Xe", "Xe")
                        .WithMany()
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.NhanVien", b =>
                {
                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.NhaXe", "NhaXe")
                        .WithMany()
                        .HasForeignKey("MaNhaXe")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NhaXe");
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.SoGheSoGiuong", b =>
                {
                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.Xe", "Xe")
                        .WithMany()
                        .HasForeignKey("MaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.ThanhToan", b =>
                {
                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.NhaXe", "NhaXe")
                        .WithMany()
                        .HasForeignKey("MaNhaXe")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.VeXe", "VeXe")
                        .WithMany()
                        .HasForeignKey("MaVeXe")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("NhaXe");

                    b.Navigation("VeXe");
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.VeXe", b =>
                {
                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.ChuyenXe", "ChuyenXe")
                        .WithMany()
                        .HasForeignKey("MaChuyen")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.NhaXe", "NhaXe")
                        .WithMany()
                        .HasForeignKey("MaNhaXe")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.SoGheSoGiuong", "SoGheSoGiuong")
                        .WithMany()
                        .HasForeignKey("MaSoGhe", "MaXe")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChuyenXe");

                    b.Navigation("KhachHang");

                    b.Navigation("NhaXe");

                    b.Navigation("NhanVien");

                    b.Navigation("SoGheSoGiuong");
                });

            modelBuilder.Entity("QuanLyBanVeXeBenXeMienDong.Models.HeThong.Xe", b =>
                {
                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.LoaiXe", "LoaiXe")
                        .WithMany()
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBanVeXeBenXeMienDong.Models.HeThong.NhaXe", "NhaXe")
                        .WithMany()
                        .HasForeignKey("MaNhaXe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiXe");

                    b.Navigation("NhaXe");
                });
#pragma warning restore 612, 618
        }
    }
}
